project: 
  type: website

website: 
  title: "Revathy Venugopal"
  navbar:
    search: true
  sidebar:
    contents: 
      - href: src/index.qmd
        text: Home
      - section: "Posts"
        contents:
          - src/posts/post_1.qmd
          - src/posts/post_2.qmd

# format: 
#   html: 
#     theme: 
#       light: flatly
#       dark: darkly
#     toc: true
#     css: styles.css
# execute: 
#   freeze: auto

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
