project: 
  type: website

website: 
  page-footer: "Copyright © 2025 Revathy Venugopal"
  title: "Revathy Venugopal"
  description: "Portfolio of Revathy Venugopal - AI/ML Engineer & Python Developer"
  navbar:
    search: true
    tools:
      - icon: github
        href: https://github.com/Revathyvenugopal162/
      - icon: linkedin  
        href: https://www.linkedin.com/in/revathy-venugopal-3310b5147/
      - icon: envelope
        href: mailto:revathyvenugopal162@gmail.com
  sidebar:
    contents: 
      - href: index.qmd
        text: "Home"
      - section: "Blog Posts"
        contents:
          - href: posts/ai-ml-journey.qmd
            text: "AI/ML Journey"
          - href: posts/search-solutions-evolution.qmd
            text: "Search Solutions Evolution"

# format: 
#   html: 
#     theme: 
#       light: flatly
#       dark: darkly
#     toc: true
#     css: styles.css
# execute: 
#   freeze: auto

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    toc-location: left
    smooth-scroll: true
    anchor-sections: true
    code-fold: false
    code-tools: false
    highlight-style: github
    fig-responsive: true

execute: 
  freeze: auto

metadata-files:
  - _metadata.yml
