project: 
  type: website

website: 
  title: "My Website"
  sidebar: 
    contents: 
      - about.qmd
      - revathy-venugopal.qmd

format: 
  html: 
    theme: 
      light: flatly
      dark: darkly
    toc: true
execute: 
  freeze: auto