name: Build LaTeX document

on:
  pull_request:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  make_linux:
    name: Build with Makefile - Linux
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install LaTeX build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexmk texlive-fonts-extra
          sudo apt install graphicsmagick-imagemagick-compat

      - name: Run the Makefile
        run: |
          make all

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: Revathy-venugopal-CV-MAKEFILE-LINUX
          path: resume/out/revathy-venugopal.pdf
          retention-days: 7

  build_latex: 
    name: Build the LaTeX CV
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Install LaTeX build tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y latexmk texlive-fonts-extra
          sudo apt install graphicsmagick-imagemagick-compat

      - name: Run the Makefile
        run: |
          make all

      - name: "Set up Quarto"
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: "Render the website"
        run: quarto render

      - name: "Upload the website"
        uses: actions/upload-artifact@v4
        with:
          name: Revathy-venugopal-CV-WEBSITE
          path: _site/
          retention-days: 7

      - name: Upload PDF as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: Revathy-venugopal-CV
          path: resume/out/revathy-venugopal.pdf
          retention-days: 7

      - name: Prepare for deployment
        run: |
          mkdir -p site
          cp -r _site/* site/
          cp resume/out/revathy-venugopal.pdf site/
          cp resume/out/revathy-venugopal.png site/

      - name: Deploy CV to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository-name: Revathyvenugopal162/revathyvenugopal162.github.io
          branch: main 
          folder: site
          clean: true
          single-commit: true

      - name: Create a CV release
        # if: github.event_name == 'push' && contains(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            resume/out/revathy-venugopal.pdf